=== MuraTools/Mura-Tools-for-Eclipse-Core/static/MuraThemes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:muratools="http://muratools.com/MuraThemes/" targetNamespace="http://muratools.com/MuraThemes/">
    <complexType name="MuraTheme">
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="fileName" type="string" use="required"></attribute>
    	<attribute name="url" type="string" use="required"></attribute>
    </complexType>

    <complexType name="MuraThemeCollection">
    	<sequence>
    		<element name="theme" type="muratools:MuraTheme" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="themeCollection" type="muratools:MuraThemeCollection"></element>

    <element name="theme" type="muratools:MuraTheme"></element>
</schema>

=== MuraTools/Mura-Tools-for-Eclipse-Core/static/MuraThemes.xml
<?xml version="1.0" encoding="UTF-8"?>
<muratools:themeCollection xmlns:muratools="http://muratools.com/MuraThemes/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://muratools.com/MuraThemes/MuraThemes.xsd ">
  <theme url="http://getmura.com/marketplace/apps/960-grid-system/" name="960 Grid System" fileName="960-grid.zip"/>
  <theme url="http://getmura.com/marketplace/apps/blueprint-css/" name="Blueprint CSS" fileName="blueprint.zip"/>
  <theme url="http://getmura.com/marketplace/apps/cosumnes/" name="Cosumnes" fileName="cosumnes.zip"/>
  <theme url="http://getmura.com/marketplace/apps/html-5-boilerplate/" name="HTML5 Boilerplate" fileName="html5boilerplate.zip"/>
  <theme url="http://getmura.com/marketplace/apps/merced-site-bundle/" name="Merced" fileName="merced.zip"/>
  <theme url="http://getmura.com/marketplace/apps/merced-site-bundle/" name="Merced HTML5" fileName="merced-html5.zip"/>
  <theme url="http://getmura.com/marketplace/apps/merced-lite/" name="Merced Lite" fileName="merced-lite.zip"/>
</muratools:themeCollection>
